# Setup
title:               Héctor Delgado,
tagline:             PhD
description:         ''
url:                 https://h-delgado.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Héctor Delgado
  url:               https://
  email:             hecdelflo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
